-- 1. PLEDGES TABLE (서약서)
create table if not exists pledges (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  affiliation text not null
);

-- 2. POSTS TABLE (인증샷)
create table if not exists posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null,
  title text not null,
  likes bigint default 0
);

-- 3. MESSAGES TABLE (응원 메시지)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  author text not null
);

-- 4. ENABLE RLS (Row Level Security) - This is critical for security but default is off for new tables often
alter table pledges enable row level security;
alter table posts enable row level security;
alter table messages enable row level security;

-- 5. POLICIES (Allow public access for this simple app)
-- Note: In a real production app, you might want stricter policies.

-- Pledges Policies
create policy "Enable read access for all users" on pledges for select using (true);
create policy "Enable insert access for all users" on pledges for insert with check (true);

-- Posts Policies
create policy "Enable read access for all users" on posts for select using (true);
create policy "Enable insert access for all users" on posts for insert with check (true);
create policy "Enable update (likes) for all users" on posts for update using (true);
create policy "Enable delete for all users" on posts for delete using (true);

-- Messages Policies
create policy "Enable read access for all users" on messages for select using (true);
create policy "Enable insert access for all users" on messages for insert with check (true);
create policy "Enable delete for all users" on messages for delete using (true);

-- 6. STORAGE BUCKET (photos)
-- Attempt to create bucket 'photos' if it doesn't exist
insert into storage.buckets (id, name, public) 
values ('photos', 'photos', true)
on conflict (id) do nothing;

-- 7. STORAGE POLICIES
create policy "Give public access to photos" on storage.objects for select using ( bucket_id = 'photos' );
create policy "Enable upload for all users" on storage.objects for insert with check ( bucket_id = 'photos' );
create policy "Enable delete for all users" on storage.objects for delete using ( bucket_id = 'photos' );
